site_name: OmegaT manual sandbox documentation
docs_dir: developer
site_dir: ../build/docs/developer/
markdown_extensions:
  - tables
  - def_list
  - footnotes
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

theme:
  name: material
  features:
  - navigation.tracking
  - navigation.top
